In [3]:
import numpy as np
mycorpus = ["I am playing cricket today", "He is playing football"]

In [7]:
import keras
from tensorflow.keras.preprocessing.text import Tokenizer
mytokenizer = Tokenizer()

In [8]:
mytokenizer.fit_on_texts(mycorpus)

In [10]:
print(mytokenizer.word_index)

{'playing': 1, 'i': 2, 'am': 3, 'cricket': 4, 'today': 5, 'he': 6, 'is': 7, 'football': 8}


In [11]:
mysequences = mytokenizer.texts_to_sequences(mycorpus)
mysequences

[[2, 3, 1, 4, 5], [6, 7, 1, 8]]

In [13]:
from keras.utils import pad_sequences
mypaddedsequence = pad_sequences(mysequences , padding = 'pre')
mypaddedsequence

array([[2, 3, 1, 4, 5],
       [0, 6, 7, 1, 8]], dtype=int32)

In [14]:
from keras import models,layers

model = models.Sequential()
model.add(layers.Embedding(9, output_dim = 3 , input_length = 5))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.compile('adam','accuracy')
pred = model.predict(mypaddedsequence)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 547ms/step


array([[[ 0.00637957, -0.02836367, -0.04697433],
        [ 0.03640613, -0.01727781,  0.03531085],
        [ 0.02455712, -0.00023854, -0.03028201],
        [-0.00171397, -0.02326633, -0.03575897],
        [-0.0495163 , -0.04168079,  0.04086653]],

       [[-0.01318203, -0.02079377,  0.03250097],
        [ 0.00464729,  0.02754713, -0.00226497],
        [-0.04751227,  0.00565814,  0.04595404],
        [ 0.02455712, -0.00023854, -0.03028201],
        [ 0.04707116,  0.00682103, -0.00208559]]], dtype=float32)

**Text Classification**

In [16]:
#Data
texts = [
    "I am playing good cricket",
    "He is playing chess",
    "I like to watch cricket",
    "Chess is a mind game",
    "Cricket is played outdoors",
    "Chess pieces are intresting",
    "We played cricket yesterday",
    "He won the chess match"
    ]

In [38]:
#Target - cricket -> 0 , chess -> 1
labels = [0 , 1 , 0 , 1 , 0 , 1 , 0 , 1]

In [39]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from tensorflow.keras import models, layers

In [40]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts(texts)

In [41]:
mysequences = mytokenizer.texts_to_sequences(texts)
mypaddedsequence = pad_sequences(mysequences , padding = 'pre')
print(mypaddedsequence)

[[ 4  8  5  9  1]
 [ 0  6  3  5  2]
 [ 4 10 11 12  1]
 [ 2  3 13 14 15]
 [ 0  1  3  7 16]
 [ 0  2 17 18 19]
 [ 0 20  7  1 21]
 [ 6 22 23  2 24]]


In [42]:
mypaddedsequence.max()

np.int32(24)

In [33]:
X = mypaddedsequence.astype(int)
y = labels

In [34]:
X.shape

(8, 5)

In [35]:
print(type(X))

<class 'numpy.ndarray'>


In [45]:
import tensorflow as tf

model = models.Sequential()
model.add(layers.Embedding(25, output_dim = 3 , input_length = 5))

#RNN layer
model.add(keras.layers.SimpleRNN(units = 5 , activation = 'tanh'))
model.add(keras.layers.Dense(units = 1 , activation = 'sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [46]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_5 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
#compile
model.compile(optimizer = 'rmsprop' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [51]:
X = np.array(X)
X

array([[ 4,  8,  5,  9,  1],
       [ 0,  6,  3,  5,  2],
       [ 4, 10, 11, 12,  1],
       [ 2,  3, 13, 14, 15],
       [ 0,  1,  3,  7, 16],
       [ 0,  2, 17, 18, 19],
       [ 0, 20,  7,  1, 21],
       [ 6, 22, 23,  2, 24]])

In [53]:
y = np.array(y)

In [54]:
#fit to train
model.fit(X,y,epochs = 10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.8750 - loss: 0.6768
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8750 - loss: 0.6640
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.6538
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.6447
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 1.0000 - loss: 0.6362
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.6280
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.6201
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.6123
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.6046
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.5970


In [62]:
#new_text = "Today we have a cricket match"
new_text = "TIt was nice chess game"

mytokenizer.texts_to_sequences([new_text])

[[2, 15]]

In [63]:
pad_sequences(mytokenizer.texts_to_sequences([new_text]) , padding = 'pre' , maxlen=5)

array([[ 0,  0,  0,  2, 15]], dtype=int32)

In [64]:
print(model.predict(pad_sequences(mytokenizer.texts_to_sequences([new_text]) , padding = 'pre' , maxlen=5)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[0.50857526]]


In [65]:
print(np.round(model.predict(pad_sequences(mytokenizer.texts_to_sequences([new_text]) , padding = 'pre' , maxlen=5))))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[1.]]
